3 lesson homework
Prokopyevt/course-spring pull request #3
Opened 2020-11-22 15:34 UTC by Prokopyevt

2020-11-22 23:39 UTC, Korgutlova requested changes
Так вроде требования с добавлением авторизации и ролей выполнены, однако в работе я не увидела permissions (разрешений)

2020-11-22 23:39 UTC, Korgutlova commented on src/main/java/com/simbirsoft/springcourse/config/SecurityConfig.java
> +
пустые строки убираем (форматирование)

2020-11-22 23:39 UTC, Korgutlova commented on src/main/java/com/simbirsoft/springcourse/service/security/UserDetailsServiceImpl.java
> +    @Service
форматирование слетело, отступ

2020-11-22 23:39 UTC, Korgutlova commented on src/main/java/com/simbirsoft/springcourse/model/User.java
> +    public Long getId() {
для удобства можно использовать lombok

2020-11-23 18:32 UTC, ramilmm commented on src/main/java/com/simbirsoft/springcourse/model/User.java
> +    public Long getId() {
> для удобства можно использовать lombok

об этом на следующем занятии)

2020-11-23 18:47 UTC, ramilmm commented on src/main/java/com/simbirsoft/springcourse/model/User.java
> +@Table(name = "userdata")
Может переименовать таблицу в "users"?

2020-11-23 18:47 UTC, ramilmm commented on src/main/java/com/simbirsoft/springcourse/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
@Repository?

2020-11-25 22:47 UTC, Korgutlova approved these changes
Отлично что добавил пермишены! Можешь мержить.

2020-11-25 22:47 UTC, Korgutlova commented on src/main/resources/db/migration/V2_0_0_1__userbase.sql
> +INSERT INTO users (id, username, password) VALUES (1, 'Ivan', '$2y$12$GEiD1FfhRc22AqgF8kmJwe51nknKX4B9nTfIytCjJC4Ps9CViLGAy');
миграции не меняем, а добавляем новые  если что-то хотим поменять (даже если это название)  

на будущее надо запомнить

2020-11-26 04:09 UTC, merged