Домашнее задание 4 урока
Prokopyevt/course-spring pull request #4
Opened 2020-11-29 12:38 UTC by Prokopyevt

1. Добавлен Lombok
2. Добавлен mapstruct
3. Добавлен swagger

2020-11-29 18:56 UTC, Korgutlova requested changes
В задании про swagger было сказано : "Добавить описания полей, методов, ответов от эндпоинта, добавить примеры ответов аннотациями" 

У тебя сделано описание методов с помощью `@ApiParam` правда это используется обычно для входных параметров, а для описания метода используется `@ApiOperation`  так же еще можно ипользовать `@ApiResponse` или `@ApiResponses` для описаний кодов ответа. 

Пожалуйста добавь эти изменения также.

2020-11-29 18:56 UTC, Korgutlova commented on src/main/java/com/simbirsoft/springcourse/service/Impl/LibraryServiceImpl.java
> +    private LibraryMapper libraryMapper;
final модификатор  (для всех остальных тоже, где еще встречается)

2020-11-29 18:56 UTC, Korgutlova commented on src/main/java/com/simbirsoft/springcourse/service/Impl/ReaderServiceImpl.java
> +        //    throw new NullPointerException("Пустое значение");
удаляем неиспользуемый код

2020-11-29 18:56 UTC, Korgutlova commented on pom.xml
> +			<version>1.4.1.Final</version>
значения версий обычно выносят в пропертис , где у тебя указана версия java

2020-11-30 23:26 UTC, Korgutlova approved these changes
В принципе можно было для `@ApiParam` которые ты указал в модели добавить и example , но в целом и так все хорошо) 

Пример `@ApiParam(required = true, value = "Имя читателя", example="Вася")`

2020-12-01 19:04 UTC, ramilmm commented on src/main/java/com/simbirsoft/springcourse/service/Impl/LibraryServiceImpl.java
> +           throw new NullPointerException("Пустое значение");
эта проверка будет автоматически сгенерена внутри метода маппера. Но если ты хочешь тут просто вывести свою ошибку с текстом, то ок

2020-12-03 06:06 UTC, Prokopyevt commented on src/main/java/com/simbirsoft/springcourse/service/Impl/LibraryServiceImpl.java
> +           throw new NullPointerException("Пустое значение");
Могу ли я замержить эту ветку ?

2020-12-04 05:45 UTC, ramilmm approved these changes
В целом ок, посмотри мой коммент насчёт добавления @Schema в ответы. Аннотация @Schema внутри @ApiResponse описывает примерную структуру ответа от сервера. То есть в интерфейсе сваггера будет видна структура этих классов. Это не критичное замечание, можешь смёржить сейчас, если не хочешь это добавлять.

2020-12-04 05:45 UTC, ramilmm commented on src/main/java/com/simbirsoft/springcourse/controller/ReaderController.java
> +    @ApiResponses(value = {@ApiResponse(code = 200, message = "Запрос успешно выполнен"),
тут можно в описание кода 201 добавить модель ответа @Schema

2020-12-04 05:45 UTC, ramilmm commented on src/main/java/com/simbirsoft/springcourse/controller/ReaderController.java
> +    @ApiResponses(value = {@ApiResponse(code = 200, message = "Запрос успешно выполнен"),
тут можно в описание кода 200 добавить модель ответа @Schema
Но это не критично, просто можешь потом сам добавить, если захочешь. Если добавишь @Schema, то в сваггере будет видна структура шаблонного ответа, то есть класса Reader.

2020-12-04 10:53 UTC, merged